apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-quota
  namespace: dev
spec:
  hard:
    cpu: 2
    memory: 2G
    pods: 20
    services: 20
    replicationcontrollers: 20
    resourcequotas: 2
